BuildFire/sdk

plugins/examplePlugin/control/content/index.html
scripts/buildfire.js

open ImageLib and insert the callback result for selected image url in background textbox.

add sample code for ImageLib in examplePlugin

---

styles/pluginScreen.css
styles/siteStyle.css

Updated styles.

---

pluginTester/scripts/siteConfig.js

Fix for https://github.com/BuildFire/sdk/issues/31

add appHost in shell to enable appearance api

---

pluginTester/shell.html

modified sandbox attributes of widget iframe

---

pluginTester/shell.html
styles/appStyle.css
styles/bootstrap.css
styles/helper.css
styles/pluginScreen.css
styles/siteStyle.css

Updated styles and added siteIcons to shell.html

Updated styles and added siteIcons to shell.html

---

styles/appStyle.css
styles/bootstrap.css
styles/siteStyle.css

Updates to siteStyle, appStyle, and bootstrap.

Updates to siteStyle, appStyle, and bootstrap.

---

scripts/buildfire/components/carousel/carousel.js
scripts/buildfire/components/sortableList/sortableList.js

Replace innerText with innerHTML
add class hide-empty to the main container

Carousel Component

---

scripts/buildfire/components/actionItems/sortableList.js
scripts/buildfire/components/carousel/carousel.js

Fix Carousel items array issues
Complete actionItems sortableList

Carousel changes and actionItems sortable list

---

scripts/buildfire/components/carousel/carousel.js

re-implement the HTML of the widget
remove margin-bottom-fifteen
if item action is empty label to edit button "add action" else "edit action"

Changes on the carousel component

---

scripts/buildfire/components/pluginInstance/sortableList.js

load items from the plugin instances either as array or object of objects

Plugin instances

---

scripts/buildfire.js

Add getWithDynamicData option for datastore

getWithDynamicData

---

styles/appStyle.css
styles/siteStyle.css

Updated appStyle and siteStyle

Updated appStyle and siteStyle

---

scripts/buildfire/components/images/thumbnail.js

* title: to change thumbnail label
* dimensionsLabel: to show a label under the thumbnail about the best resolution to upload
- please see the wiki for more info https://github.com/BuildFire/sdk/wiki/BuildFire-Thumbnail-Component

Add options to the thumbnail component

---

scripts/buildfire/components/pluginInstance/sortableList.js

* Return all added items to onAddItems method when adding new items

plugin instances component:

---

scripts/buildfire/components/carousel/carousel.js
scripts/buildfire/components/notifications/notifications.js
scripts/buildfire/components/pluginInstance/sortableList.js

Add load all plugins to plugin instances
implement buildfire.notifications.confirm

plugin instances and notifications components

---

styles/appStyle.css
styles/bootstrap.css
styles/siteStyle.css

Update appStyle, siteStyle, and bootstrap.

Update appStyle, siteStyle, and bootstrap.

---

styles/appStyle.css
styles/page-transition.css
styles/siteStyle.css

Update appStyle and siteStyle. Introduce page-transition.css for slide Animations.a

Update appStyle and siteStyle. Introduce page-transition.css for slide Animations.a

---

styles/appStyle.css
styles/helper.css

Fix side scrolling in app. Style for no background on sliders. Update appStyle and helper.

Fix side scrolling in app. Style for no background on sliders. Update appStyle and helper.

---

scripts/tinymce/skins/lightgray/skin.min.css
styles/appStyle.css
styles/bootstrap.css
styles/pluginScreen.css
styles/siteStyle.css
styles/transitionAnimation.css

Update appStyle, bootstrap, pluginScreen, siteStyle, and transitionAnimation. Update tinymce css.

Update appStyle, bootstrap, pluginScreen, siteStyle, and transitionAnimation. Update tinymce css. 

---

styles/appStyle.css

Update appStyle and launcher. Fix some bugs and styling.

Update appStyle and launcher. Fix some bugs and styling.

---

styles/appStyle.css
styles/transitionAnimation.css

Updates to appStyle and transitionAnimation. Fix for fixed nav.

Updates to appStyle and transitionAnimation. Fix for fixed nav.

---

pluginTester/pages/templates/settings.html
scripts/buildfire.js
scripts/buildfire/components/carousel/carousel.js
styles/appStyle.css
styles/bootstrap.css

Carousel bug fixed. Updated html enabled to be widget and control. Cleaned up settings UI. Updated bootstrap and appStyle.

Carousel bug fixed. Updated html enabled to be widget and control. Cleaned up settings UI. Updated bootstrap and appStyle.

---

scripts/tinymce/skins/lightgray/skin.min.css
styles/appStyle.css
styles/bootstrap.css
styles/loading.css
styles/siteStyle.css

Update appStyle, bootstrap, and siteStyle.

Update appStyle, bootstrap, and siteStyle.

---

scripts/buildfire/components/carousel/carousel.js
styles/appStyle.css
styles/bootstrap.css
styles/helper.css

Update appStyle and bootstrap. Adjust owlCarousel timing. Fix WYSIWYG bullet points css.

Update appStyle and bootstrap. Adjust owlCarousel timing. Fix WYSIWYG bullet points css.

---

scripts/tinymce/skins/lightgray/skin.min.css
styles/appStyle.css
styles/bootstrap.css
styles/siteStyle.css

Update tinymce styling. Make add photo green + icon appear behind image. Update appStyle and bootstrap.

Update tinymce styling. Make add photo green + icon appear behind image. Update appStyle and bootstrap.

---

scripts/buildfire/components/carousel/carousel.js

https://github.com/BuildFire/customerServiceTickets/issues/352

https://github.com/BuildFire/customerServiceTickets/issues/352

---

scripts/buildfire.js

add options to historyAPI get function to enable pluginBreadcrumbsOnly option

add options to historyAPI get

---

styles/appStyle.css
styles/pluginScreen.css
styles/siteStyle.css

update appStyle and siteStyle.

update appStyle and siteStyle.

---

plugins/examplePlugin/widget/index.html

remove widget analytics that are too frequent

remove widget analytics

---

scripts/tinymce/skins/lightgray/skin.min.css
styles/appStyle.css
styles/bootstrap.css
styles/siteStyle.css

Clean up UI for login on SDK. Clean up tinymce UI. Update appStyle, bootstrap, and siteStyle.

Clean up UI for login on SDK. Clean up tinymce UI. Update appStyle, bootstrap, and siteStyle.

---

scripts/buildfire.js

this commit updates the launcher and widget with appearance updates

reflect appearance updates to launcher and widget

---

pluginTester/scripts/overrides.js

Fix controlIFrame not found in DOM at override execution time

Fix controlIFrame null

---

scripts/buildfire.js

buildfire.js method for device sharing functionality

add device sharing functionality

---

pluginTester/index.html
scripts/tinymce/skins/lightgray/skin.min.css
styles/appStyle.css
styles/siteStyle.css

Update appStyle, siteStyle, and tinymce css. Adjust UI for widget on SDK.

Update appStyle, siteStyle, and tinymce css. Adjust UI for widget on SDK.

---

scripts/buildfire/components/carousel/carousel.js
scripts/buildfire/components/pluginInstance/sortableList.js

https://github.com/BuildFire/customerServiceTickets/issues/1410

https://github.com/BuildFire/customerServiceTickets/issues/1410

---

scripts/tinymce/skins/lightgray/skin.min.css
styles/siteStyle.css

Update tinymce UI. Update siteStyle.

Update tinymce UI. Update siteStyle.

---

styles/pluginScreen.css
styles/siteStyle.css

Update siteStyle and pluginScreen for new list-view UI.

Update siteStyle and pluginScreen for new list-view UI.

---

pluginTester/pages/controllers/shellCtrl.js
pluginTester/pages/templates/shell.html
pluginTester/scripts/loadScripts.js
pluginTester/scripts/overrides.js

adds breadcrumbs in plugin tester view and allows user to test breadcrumbs.

breadcrumbs support in developer plugin tester

---

scripts/buildfire/components/carousel/carousel.js
styles/siteStyle.css

Update siteStyle to hide deep links. Remove tooltip from carousel component.

Update siteStyle to hide deep links. Remove tooltip from carousel component.

---

scripts/buildfire/components/carousel/carousel.js

Update verbiage for carousel component action links.

Update verbiage for carousel component action links.

---

scripts/buildfire/components/carousel/carousel.js

Revert lazyLoad.

---

scripts/buildfire.js
scripts/buildfire/components/carousel/carousel.js
styles/siteStyle.css

Add minHeight to carousel. Add forceCSSRender to redraw plugin to fix text scroll issue. Update siteStyle.

Add minHeight to carousel. Add forceCSSRender to redraw plugin to fix text scroll issue. Update siteStyle.

---

styles/appStyle.css

Update appStyle to remove all plugin css.

 Update appStyle to remove all plugin css.

---

scripts/buildfire/components/carousel/carousel.js
styles/appStyle.css

Fix bug with carousel minHeight. Update appStyle.

Fix bug with carousel minHeight. Update appStyle.

---

scripts/buildfire.js
styles/bootstrap.css
styles/pluginScreen.css
styles/siteStyle.css

Text plugin scroll issue fix. Update bootstrap and siteStyle css.

Text plugin scroll issue fix. Update bootstrap and siteStyle css.

---

scripts/buildfire.js

This code is updated so that to avoid use of SSL and image can be easily accessible from cloud with any link broken or some other issues.

HTTPS  URL for all images which are cropped in buildfire.js are updated to HTTP URL

---

scripts/buildfire.js

disabled buildfire.js to resend bulkInsert request if callback is not received

---

styles/bootstrap.css

Fix tabs for plugins. Create UI for bootstrap modals on app.

Fix tabs for plugins. Create UI for bootstrap modals on app.

---

scripts/tinymce/skins/lightgray/skin.min.css
styles/appStyle.css
styles/siteStyle.css

Update tinymce UI. Update appStyle and siteStyle. Add tab css on cp side.

Update tinymce UI. Update appStyle and siteStyle. Add tab css on cp side.

---

styles/appStyle.css
styles/bootstrap.css

Update appStyle and bootstrap css

Update appStyle and bootstrap css

---

pluginTester/scripts/loadScripts.js
plugins/myPlugin/plugin.json

fixes malformed json and adds a future reference to remoteDatastore.js so it is available on our next deployment

fix myPlugin plugin.json and add future reference to remoteDatastore.js

---

scripts/buildfire.js

getFrameType APi provided to check if current plugin is Home plugin or something else

---

pluginTester/pages/controllers/shellCtrl.js

fix pluginTester pluginData not being sent to historyAPI

---

pluginTester/pages/controllers/shellCtrl.js
pluginTester/pages/templates/shell.html
styles/siteStyle.css

add custom tabs support for plugin tester

custom tabs support for plugin tester

---

pluginTester/scripts/loadScripts.js
scripts/buildfire.js

adding publicDatastoreApi to pluginTester load script
check if the url has https to be http incase prod env

adding publicDatastoreApi to pluginTester, fix image loading

---

scripts/buildfire/services/commerce/inAppPurchase.js
styles/appStyle.css

add in-app purchases service

---

.gitignore
scripts/buildfire.js
scripts/buildfire/components/carousel/carousel.js

adding two events onAppLauncherActive and onAppLauncherInactive
these events triggered from app once open the launcher and open the plugin

onAppLauncherActive and onAppLauncherInactive

---

pluginTester/scripts/loadScripts.js

Update Path to match the new file structure

Update Path 

---

pluginTester/scripts/overrides.js

https://github.com/BuildFire/sdk/issues/358

Path bug in SDK

---

pluginTester/index.html

fix undefiend issue when hidding the titlebar "buildfire.appearance.titlebar.hide()", and remove the padding on widget iframe when hide the title bar

fix title bar hide issue

---

scripts/buildfire.js

WIP refactor of packet retry

---

pluginTester/pages/controllers/shellCtrl.js
pluginTester/pages/templates/shell.html

https://www.pivotaltracker.com/story/show/151821956

Hide header when `coontent.removeHeader` is true in plugin.json

---

pluginTester/scripts/overrides.js

return auth profile if available instead of CP user

return auth profile if available instead of CP user

---

styles/siteStyle.css

migrate new imageLib styles to plugin tester to fix broken stock images layout

migrate new imageLib styles to plugin tester

---

pluginTester/app.js
pluginTester/index.html
pluginTester/scripts/angular/angular-color-picker.js
pluginTester/scripts/loadScripts.js
pluginTester/styles/angular-color-picker.css
scripts/buildfire.js

add Color Component for SDK

---

pluginTester/index.html
pluginTester/pages/controllers/shellCtrl.js
pluginTester/scripts/siteConfig.js
scripts/buildfire.js
styles/siteStyle.css

This feature gives customer option to test and work on different device screens inside SDK, simply by selecting device name from select box on top of emulator.

sdk emulator device sizes, bf getcontext if widget pathname

---

package.json
scripts/buildfire/components/carousel/carousel.js

Add responsive option to carousel

Responsive Carousel

---

pluginTester/pages/controllers/indexCtrl.js

change mechanism to check sdk version to be everyday

Github rate limit

---

scripts/tinymce/plugins/actionitem/plugin.min.js

escape special characters

---

scripts/buildfire/components/ratingSystem/index.css
scripts/buildfire/components/ratingSystem/index.js

5 star rating system

---

scripts/buildfire/components/control/listView/listView.js
styles/components/control/listView/listView.css

add disabling drag option so the developer can force rows to be in fixed position (top/bottom) of the control list view

feat(control list view): add disable drag option

---

scripts/buildfire/components/swipeableDrawer/swipeableDrawer.js

remove prevent default from swipeable drawer header touchend so the click event can be fired

fix(swipeableDrawer): remove prevent default
